### ISSUE TITLE
Please drop autogen.sh, it is not required anymore IMHO

### ISSUE THREAD

**Issue by sunweaver** [Ozzyboshi/guake-indicator#11]
This should solve Debian bug DBTS#829883. The configure.ac uses non of the gnome-common macros anymore.

With it, please drop gnome-common from Build-Depends: in debian/control.

**Comment by Ozzyboshi** [comment]
gnome-common and autogen.sh dropped because deprecated, see commit 

https://github.com/Ozzyboshi/guake-indicator/commit/5e81c9ca79c5315f6a22a86b3a2357146189be8f
