### ISSUE TITLE
Please move the man page from debian/guake-indicator.1 to the base path or the data dir.

### ISSUE THREAD

**Issue by sunweaver** [Ozzyboshi/guake-indicator#12]
The subject says it all. The man page is part of your upstream project and should be placed there. Please also adapt the installation of the man page into the package then.

**Comment by Ozzyboshi** [comment]
I created a new man directory on the root of the project and moved the man file from debian to man.
Changed makefile.am/s and configure.ac accordingly and deleted every reference to the man from the debian directory. I hope it's OK with you if i didn't use the root directory or the data directory.
See commit https://github.com/Ozzyboshi/guake-indicator/commit/e5affe08a88f942ca15bbb21dda92cd233b05671

**Comment by sunweaver** [comment]
Looks good.
