### ISSUE TITLE
Make edit screen scrollable for lowres

### ISSUE THREAD

**Issue by Ozzyboshi** [Ozzyboshi/guake-indicator#14]
The edit menu screen is almost unusable for lowres screen, for example 1366 x 768.
The solution in this case could be to make the window scrollable.
This is a screenshot for reference.

![selection_062](https://user-images.githubusercontent.com/4318885/45403955-46bff880-b65d-11e8-9faf-1454ba1805c4.png)

When fixed contact "tim O": z0rk (at) carukia dot net

**Comment by bunyamink** [comment]
Still same problem...

**Comment by Ozzyboshi** [comment]
working on in , dont have a solution yet

**Comment by Ozzyboshi** [comment]
For now you could try this glade, overwrite this one with /usr/local/share/guake-indicator/gi_edit_menu_dialog.glade


[gi_edit_menu_dialog.glade.zip](https://github.com/Ozzyboshi/guake-indicator/files/4605428/gi_edit_menu_dialog.glade.zip)
