### ISSUE TITLE
error: cannot find input file: plugins/Makefile.in [ArchLinux MATE]

### ISSUE THREAD

**Issue by buzzworkers** [Ozzyboshi/guake-indicator#3]
i installed Guake from AUR repo & it's working nicely but i miss Guake-Indicator & ti's plugins. 
so I'm trying to compile this in archlinux, had to make sure to have autoconf & libappindicator are installed & then run 
  ./configure && make && make instal

but  along the compile process i get this : 

configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating data/Makefile
config.status: error: cannot find input file: `plugins/Makefile.in'

it seems there is no https://github.com/Ozzyboshi/guake-indicator/tree/master/plugins such file at this place neither, so i was wondering if i'm doing something wrong or if the indicator part is not possible to use with archlinux-Mate

**Comment by Ozzyboshi** [comment]
did you try to run autorecong before running /configure && make && make install ?
