### ISSUE TITLE
Not compatible with guake 3.0.4 version

### ISSUE THREAD

**Issue by infomatico** [Ozzyboshi/guake-indicator#4]
Hello,

Not compatible with guake 3.0.4 version.

**Comment by Ozzyboshi** [comment]
I know, dbus hooks are different, I will release a new guake-indicator version, probably it will be guake3-indicator

**Comment by infomatico** [comment]
Cool!! Thanks for your quick answer Ozzyboshi!!! :+1:

**Comment by Ozzyboshi** [comment]
I fixed Guake (not guake indicator) with commit f7d72f5 (more on https://github.com/Guake/guake/commit/f7d72f5fc57d4843575e4763094354100124bbc3 ).
Now, if you change the following defines from src/guake-indicator-dbus.h

#define GUAKE_URI "org.guake.RemoteControl"
#define GUAKE_PATH "/org/guake/RemoteControl"
#define GUAKE_IFACE "org.guake.RemoteControl"

to 

#define GUAKE_URI "org.guake3.RemoteControl"
#define GUAKE_PATH "/org/guake3/RemoteControl"
#define GUAKE_IFACE "org.guake3.RemoteControl"

Guake indicator will interact with the new guake3

Of course you will have to update your local Guake3 repository with git pull to get my patch.
Still evaluating if it's better to let the guake indicator choose the interation or force it with the new guake3.
Another possibility is to fork guake-indicator and release guake3-indicator

**Comment by Ozzyboshi** [comment]
Just released guake-indicator 1.3, compile it and start it with the -guake3 switch.
Let me know id you have any issues.
Thanks

**Comment by WyoMurf** [comment]
Isn't there some easy way to detect what version of guake is installed or running, and set a mode for 0.x.x vs 3.x.x?
