### ISSUE TITLE
No application icon in the tray.

### ISSUE THREAD

**Issue by Krzysztofci** [Ozzyboshi/guake-indicator#6]
Hello, as I wrote earlier, after compiling version 1.3.1, the program icon does not appear, but the program works. Instead of the icon there is empty space after clicking which program menu is shown.
The system is Mint 19 based on Ubuntu bionic, cinnamon 3.8 graphic environment.

**Comment by Ozzyboshi** [comment]
did you install guake3?
the procedure is
autoreconf
./configure
make
sudo make install

I think you missed the last instruction , if not let me know, I will setup a new virtual machine and try with mint

**Comment by Ozzyboshi** [comment]
in the mean time i ask you to perform a git pull ,this will download 1.3.2 and guake3 is now the default terminal so you don't have to type -guake3 anymore

**Comment by Krzysztofci** [comment]
Ok, it works. I do not know if I made a mistake before during compilation, whether it is a 1.3.1 affliction, but at the moment the problem is averted.
Thank you and best regards.
Krzysztof

**Comment by Krzysztofci** [comment]
Unfortunately, after restarting the computer again, I do not have an icon.

**Comment by Ozzyboshi** [comment]
please check if you have the following files and if they are readable for the user who's running guake-indicator

/usr/local/share/icons/hicolor/16x16/apps/guake-indicator.png
/usr/local/share/icons/hicolor/22x22/apps/guake-indicator.png
/usr/local/share/icons/hicolor/24x24/apps/guake-indicator.png
/usr/local/share/icons/hicolor/256x256/apps/guake-indicator.png
/usr/local/share/icons/hicolor/32x32/apps/guake-indicator.png
/usr/local/share/icons/hicolor/48x48/apps/guake-indicator.png

**Comment by Krzysztofci** [comment]
Yes, I have these icons and as a user I am able to open them. There are more directories themselves than the icon.
```
.:
128x128  16x16  192x192  22x22  24x24  256x256  32x32  36x36  48x48  64x64  72x72  96x96  icon-theme.cache  scalable

```

**Comment by Ozzyboshi** [comment]
is it possible that you are running the executable under src rather the one in path?

**Comment by Ozzyboshi** [comment]
good i'll close this issue for now, reopen it at your need
